import { Injectable } from '@nestjs/common';
import * as puppeteer from 'puppeteer';
import Handlebars from 'handlebars';
import * as fs from 'fs';
import * as path from 'path';
import QRCode from 'qrcode';

@Injectable()
export class PdfService {
  async generateInvoicePdf(invoiceData: any) {
    // Resolve template path correctly in both local dev (src/) and production container
    const templatePath = fs.existsSync(path.join(process.cwd(), 'src/templates/invoice.hbs'))
      ? path.join(process.cwd(), 'src/templates/invoice.hbs')
      : path.join(process.cwd(), 'dist/src/templates/invoice.hbs');

    const templateHtml = fs.readFileSync(templatePath, 'utf-8');

    // Generate dynamic QR Code for instant payment if payment URL provided or generated
    const appUrl = process.env.APP_URL || 'http://localhost:3000';
    const paymentUrl = invoiceData.paymentUrl || `${appUrl}/payment/checkout/${invoiceData.id}`;
    let paymentQrCode = '';
    try {
      paymentQrCode = await QRCode.toDataURL(paymentUrl, {
        margin: 1,
        width: 150,
        color: {
          dark: '#0056b3',
          light: '#ffffff',
        },
      });
    } catch {
      // Fallback if QR generation fails
      paymentQrCode = '';
    }

    const templatePayload = {
      ...invoiceData,
      paymentUrl,
      paymentQrCode,
      amountRupees: (invoiceData.amount / 100).toFixed(2),
    };

    // Compile HTML with data (support ESM/CJS interop)
    const compile = Handlebars.compile ?? (Handlebars as any).default?.compile;
    const template = compile(templateHtml);
    const finalHtml = template(templatePayload);

    // Launch with container-friendly flags
    const browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
      ],
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
    });
    const page = await browser.newPage();
    await page.setContent(finalHtml, { waitUntil: 'domcontentloaded' });

    // Generate pdf buffer (Uint8Array converted to Buffer)
    const pdfUint8Array = await page.pdf({
      format: 'A4',
      printBackground: true,
    });
    await browser.close();
    return Buffer.from(pdfUint8Array);
  }

  async generatePaymentReceiptPdf(receiptData: {
    paymentId: string;
    transactionId: string;
    gateway: string;
    amount: number;
    paymentDate: Date | string;
    customerName: string;
    customerEmail: string;
    invoiceId: string;
    tenantName?: string;
  }) {
    const templatePath = fs.existsSync(path.join(process.cwd(), 'src/templates/receipt.hbs'))
      ? path.join(process.cwd(), 'src/templates/receipt.hbs')
      : path.join(process.cwd(), 'dist/src/templates/receipt.hbs');

    let templateHtml = '';
    if (fs.existsSync(templatePath)) {
      templateHtml = fs.readFileSync(templatePath, 'utf-8');
    } else {
      // Inline fallback template
      templateHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Helvetica', Arial, sans-serif; color: #333; margin: 0; padding: 40px; }
    .header { border-bottom: 2px solid #28a745; padding-bottom: 20px; text-align: center; }
    .badge { background: #28a745; color: white; padding: 6px 16px; border-radius: 20px; font-size: 14px; font-weight: bold; }
    .box { background: #f8f9fa; padding: 25px; border-radius: 8px; margin-top: 30px; border-left: 5px solid #28a745; }
    .row { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 15px; }
    .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <div class="header">
    <span class="badge">PAYMENT RECEIPT</span>
    <h2 style="margin-top: 15px; color: #28a745;">Payment Successful</h2>
  </div>
  <div class="box">
    <div class="row"><span><strong>Receipt / Payment ID:</strong></span><span>{{paymentId}}</span></div>
    <div class="row"><span><strong>Invoice ID:</strong></span><span>{{invoiceId}}</span></div>
    <div class="row"><span><strong>Customer:</strong></span><span>{{customerName}} ({{customerEmail}})</span></div>
    <div class="row"><span><strong>Payment Gateway:</strong></span><span>{{gateway}}</span></div>
    <div class="row"><span><strong>Gateway Transaction Ref:</strong></span><span>{{transactionId}}</span></div>
    <div class="row"><span><strong>Payment Date:</strong></span><span>{{paymentDate}}</span></div>
    <hr style="border: 0; border-top: 1px solid #ddd; margin: 20px 0;">
    <div class="row" style="font-size: 18px; font-weight: bold; color: #28a745;">
      <span>Total Paid:</span>
      <span>NPR {{amountRupees}}</span>
    </div>
  </div>
  <div class="footer">
    <p>This is an automated receipt generated by CMS. Thank you for your payment!</p>
  </div>
</body>
</html>`;
    }

    const compile = Handlebars.compile ?? (Handlebars as any).default?.compile;
    const template = compile(templateHtml);
    const finalHtml = template({
      ...receiptData,
      amountRupees: (receiptData.amount / 100).toFixed(2),
    });

    const browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
      ],
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
    });
    const page = await browser.newPage();
    await page.setContent(finalHtml, { waitUntil: 'domcontentloaded' });
    const pdfUint8Array = await page.pdf({
      format: 'A4',
      printBackground: true,
    });
    await browser.close();
    return Buffer.from(pdfUint8Array);
  }
}
